theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_buttons3_add:
  - tablecontrols
  - fullscreen
  - styleprops
  - spellchecker
plugins:
  - table
  - fullscreen
  - code